---
editor_options:
  chunk_output_type: console
---


```{r  echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}

knitr::opts_chunk$set(fig.align="center", echo=FALSE, fig.show = "hold")

```

# Example


```{r eval=FALSE}

### 1. specify the model

naive_Bayes <-
  discrim::naive_Bayes() %>%
  set_engine('klaR')

#### 2. preprocessing 

preprocess <- 
  recipe(bought ~ ., data = balanced_data) %>%
  step_string2factor(all_nominal_predictors()) %>% 
  step_impute_knn(all_predictors(), neighbors = 3) %>%
  step_scale(all_numeric_predictors())
  

#### 3, Buildworkflow

baseline_wflow <- 
  workflow() %>% 
  add_model(naive_Bayes) %>% 
  add_recipe(preprocess)

##### 4. Fit model

fit_control <- control_resamples(save_pred = TRUE, save_workflow = TRUE)

#### sets number of folds for cross validation

folds <- vfold_cv(cell_train, v = 10)

baseline_fit <- 
  baseline_wflow %>% 
  fit_resamples(folds, verbose = TRUE, control = fit_control)


#### 5. Performance metrics over the validation set
collect_metrics(baseline_fit)

```



\newpage