name: build_rproject

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read

jobs:
  render_pdf:
    runs-on: ubuntu-latest
    #container: r-base:4.1.3
    container: rocker/tidyverse
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: install dependencies
        uses: r-lib/actions/setup-r@v1
        uses: r-lib/actions/setup-pandoc@v1
        uses: r-lib/actions/setup-tinytex@v1
        run: sudo apt-get update -y && sudo apt-get -y install cmake
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
        
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "html_document")'
      
      
      - name: Commit results
        run: |
          git add index*
          git commit -m 'Re-build my-document' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      
      #- name: Restore packages
      #  shell: Rscript {0}
      #  run: |
      #    if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
      #    renv::restore()
      
      #- name: Render document
      #  run: |
      #    bookdown::render_book("index.Rmd", "bookdown::pdf_book")
      #  shell: Rscript {0}
